Refactor utils.c and provide needed header.
Tatsh/pppps2pc pull request #7
Opened 2023-04-24 16:02 UTC by movrsi

Clean up attach.c to mark dump_desc as a debug feature.

2023-04-24 23:49 UTC, Tatsh requested changes

2023-04-24 23:49 UTC, Tatsh commented on ps2-decompile/utils.h
> +#endif
```suggestion
#endif // UTILS_H
```

2023-04-24 23:49 UTC, Tatsh commented on ps2-decompile/utils.h
> +#include <usbd.h>
```suggestion
#include <stdio.h>

#include <usbd.h>

#include "callbacks.h"
#include "shared.h"
```

I want header order to be standard, 3rd party, own. They need a space between so clang-format will leave them.

2023-04-24 23:49 UTC, Tatsh commented on ps2-decompile/utils.c
> +    result = sceUsbdTransferPipe(g->dataEndpoint, &g->unk8[0x7804], g->maxPacketSize, 0,
```suggestion
    result = sceUsbdInterruptTransfer(g->dataEndpoint, &g->unk8[0x7804], g->maxPacketSize, data_transfer_done, g);
```

2023-04-25 07:29 UTC, Tatsh requested changes

2023-04-25 20:01 UTC, movrsi commented
Committed the request changes, let me know if you find anything else that may seem off.

2023-04-25 23:02 UTC, merged